'use client';

import Navbar from '../components/Navbar';
import HeroSection from '../components/HeroSection';
import FlashcardDisplay from '../components/FlashcardDisplay';
import Footer from '../components/Footer';
import { Container, Typography, Box } from "@mui/material";
import Head from "next/head";
import { useUser } from '@clerk/nextjs';
import { Accordion, AccordionSummary, AccordionDetails } from "@mui/material";
import ExpandMoreIcon from "@mui/icons-material/ExpandMore";

export default function Home() {
    const { user } = useUser(); // Get user context if needed

    return (
        <Box sx={{ display: 'flex', flexDirection: 'column', minHeight: '100vh' }}>
            <Head>
                <title>ZAPZAPCARDS</title>
                <meta name="description" content="Create FlashCards from your text" />
            </Head>
            <Navbar />
            <Box sx={{ flexGrow: 1, backgroundColor: '#f5f5f5' }}>
                <HeroSection />
                {/* Conditionally render the flashcard section only if the user is logged in */}
                {user && (
                    <Box
                      sx={{
                        width: '100%',
                        py: 6,
                        background: 'linear-gradient(-45deg, #ff69b4, #206EFF, #ff69b4, #206EFF)',
                        backgroundSize: '400% 400%',
                        animation: 'gradientBG 10s ease infinite',
                        color: 'white',
                      }}
                    >
                      <Box sx={{ maxWidth: '1200px', mx: 'auto', borderRadius: 3, overflow: 'hidden' }}>
                        <Box sx={{ textAlign: 'center', mt: 4, mb: 4 }}>
                          <Typography variant="h4" component="h2" gutterBottom sx={{ fontWeight: 600 }}>
                            Your Flashcard Sets
                          </Typography>
                          <Typography variant="body1" sx={{ color: 'white', mb: 4 }}>
                            Here are the flashcard sets you have created. Click on a card to view details.
                          </Typography>
                        </Box>
                        <FlashcardDisplay user={user} />
                      </Box>
                    </Box>
                )}
                {/* Q&A Section */}
                <Box sx={{
                  width: '100%',
                  mt: 8,
                  mb: 8,
                  display: 'flex',
                  flexDirection: 'column',
                  alignItems: 'center',
                  backgroundColor: '#f5f5f5',
                  // boxShadow: '0 4px 24px 0 rgba(0,0,0,0.08)',
                  // borderRadius: 3,
                }}>
                  <Typography variant="h4" sx={{ fontWeight: 600, mb: 3, textAlign: 'center', background: 'transparent', color: 'black' }}>
                    Frequently Asked Questions
                  </Typography>
                  <Accordion sx={{ width: '100%', maxWidth: 900 }}>
                    <AccordionSummary expandIcon={<ExpandMoreIcon />}>
                      <Typography sx={{ fontWeight: 500, textAlign: 'left' }}>Can I edit flashcards after they're generated by AI?</Typography>
                    </AccordionSummary>
                    <AccordionDetails>
                      <Typography sx={{ textAlign: 'left' }}>Yes, once flashcards are generated, you can edit, delete, or rearrange them to fit your study needs.</Typography>
                    </AccordionDetails>
                  </Accordion>
                  <Accordion sx={{ width: '100%', maxWidth: 900 }}>
                    <AccordionSummary expandIcon={<ExpandMoreIcon />}>
                      <Typography sx={{ fontWeight: 500 }}>Do I need an internet connection to use the AI generation feature?</Typography>
                    </AccordionSummary>
                    <AccordionDetails>
                      <Typography>Yes, the AI generation feature requires internet access to process and generate flashcards from your input.</Typography>
                    </AccordionDetails>
                  </Accordion>
                  <Accordion sx={{ width: '100%', maxWidth: 900 }}>
                    <AccordionSummary expandIcon={<ExpandMoreIcon />}>
                      <Typography sx={{ fontWeight: 500 }}>What kind of input can I provide to the AI?</Typography>
                    </AccordionSummary>
                    <AccordionDetails>
                      <Typography>You can input a topic or a block  of text — the AI will use this content to generate meaningful flashcards.</Typography>
                    </AccordionDetails>
                  </Accordion>
                  <Accordion sx={{ width: '100%', maxWidth: 900 }}>
                    <AccordionSummary expandIcon={<ExpandMoreIcon />}>
                      <Typography sx={{ fontWeight: 500 }}>Is there a limit to how many flashcards I can create manually?</Typography>
                    </AccordionSummary>
                    <AccordionDetails>
                      <Typography>No, you can create as many manual flashcards as you like, depending on your learning needs.</Typography>
                    </AccordionDetails>
                  </Accordion>
                  <Accordion sx={{ width: '100%', maxWidth: 900 }}>
                    <AccordionSummary expandIcon={<ExpandMoreIcon />}>
                      <Typography sx={{ fontWeight: 500 }}>What type of AI does ZapZapCards use to generate flashcards?</Typography>
                    </AccordionSummary>
                    <AccordionDetails>
                      <Typography>It uses natural language processing (NLP) to understand your input and identify key concepts, terms, and question-answer pairs.</Typography>
                    </AccordionDetails>
                  </Accordion>
                  <Accordion sx={{ width: '100%', maxWidth: 900 }}>
                    <AccordionSummary expandIcon={<ExpandMoreIcon />}>
                      <Typography sx={{ fontWeight: 500 }}>How accurate are the flashcards generated by AI?</Typography>
                    </AccordionSummary>
                    <AccordionDetails>
                      <Typography>The AI is designed to be highly accurate, but you can always review and edit flashcards to ensure they're tailored to your needs.</Typography>
                    </AccordionDetails>
                  </Accordion>
                </Box>
            </Box>
            <Footer />
            {/* Decorative Background Elements */}
            <Box
                sx={{
                    position: 'absolute',
                    top: 0,
                    left: 0,
                    width: '50vw',
                    height: '50vh',
                    borderRadius: '20%',
                    background: 'linear-gradient(to top, black, rgb(190, 18, 60))',
                    boxShadow: 3,
                    zIndex: 0,
                    filter: 'blur(70px)',
                    opacity: 0.1,
                }}
            />
            <Box
                sx={{
                    position: 'absolute',
                    bottom: 0,
                    right: 0,
                    width: '50vw', 
                    height: '50vh',
                    borderRadius: '20%',
                    background: 'linear-gradient(to top, black, rgb(190, 18, 60))',
                    boxShadow: 3,
                    zIndex: -1,
                    filter: 'blur(70px)',
                    opacity: 0.1,
                }}
            />
            <Box
                sx={{
                    position: 'absolute',
                    top: '110%',
                    left: 0,
                    width: '50vw', 
                    height: '50vh',
                    borderRadius: '20%',
                    background: 'linear-gradient(to top, black, rgb(190, 18, 60))',
                    boxShadow: 3,
                    zIndex: 0,
                    filter: 'blur(70px)',
                    opacity: 0.1,
                }}
            />
        </Box>
    );
}
